name: AdventOfCode2023
version: 0.1
github: "DanProgrammer1999/AdventOfCode2023"
license: BSD-3-Clause
author: "Danyil Dvorianov"

extra-source-files:
  - README.md

# Metadata used when publishing your package
# synopsis:            Advent of Code 2023 in Haskell
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/AdventOfCode2023#readme>

dependencies:
  - base >= 4.7 && < 5
  - text
  - containers
  - timeit
  - optparse-applicative

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs:
    - src
    - src/days

executables:
  AdventOfCode2023-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - AdventOfCode2023
